# Generated by Django 4.2.6 on 2025-05-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('title', models.TextField(max_length=100)),
                ('text', models.TextField(max_length=100)),
            ],
        ),
    ]
